### ISSUE TITLE
When user switches 'Ceiling Fan' switch from Off to Low state High state appears for a moment

### ISSUE THREAD

**Issue by IgorProtsenkoOd** [RoboDomo/robodomo-client#23]
1. Navigate Dashboard > Theater/Bedroom
2. Set 'Ceiling Fan' button to Off state by clicking on it
3. Click 'Ceiling Fan' button to change it state from Off to Low

Expected result: Button label changed from Off to Low
Actual result: Button label quickly changed from Off to High then to Low

**Comment by mschwartz** [comment]
The smartthings app changes the button to "turning off..." or "turning on..." until a message is received to acknowledge the thing was turned on or off.

The button seems to be using some state that isn't valid anymore.
