### ISSUE TITLE
On Dashboard Pool tile the text is cut if all options are on

### ISSUE THREAD

**Issue by popescunsergiu** [RoboDomo/robodomo-client#24]
Steps to reproduce:
1. Go to Autelis page and put all Pull options ON
2. Go to Dashboard > Theated
3. Inspect Pool tile

*Actual result:* Text does not fit on the 5 rows

*Expected result:* Text shall be correctly displayed

![Screenshot 2019-07-19 at 12 11 02](https://user-images.githubusercontent.com/8069082/61524302-e210bf80-aa1e-11e9-8038-ded9d470292f.png)

**Comment by mschwartz** [comment]
Not just pool:

![image](https://user-images.githubusercontent.com/329637/61818070-d8af9a80-ae04-11e9-9c72-19a69a70cacd.png)

**Comment by popescunsergiu** [comment]
![screenshot-b38aac5d9b](https://user-images.githubusercontent.com/8069082/62203516-0318cf00-b394-11e9-9531-1b57b4194299.jpeg)

**Comment by Aaron-Goldman** [comment]
fixed in #75
