### ISSUE TITLE
Pool/Spa screen issues

### ISSUE THREAD

**Issue by mschwartz** [RoboDomo/robodomo-client#32]
![image](https://user-images.githubusercontent.com/329637/61818200-3217c980-ae05-11e9-8e61-e2477f073091.png)

Sunrise and Sunset show "Invalid Date"

Outside temperature shows NaN&deg;F

Pool temperature shows 118 degrees F.  That's so hot you'd burn yourself.  It's like the temperature when you turn on the hot water in your kitchen sink.

Pool setpoint is 97 and spa is 66.  Is this swapped?

I think we can remove the macro tiles at the bottom.

When you are in pool mode and tap on Spa Heat, the main pump control (top) should change to spa (and the MQTT message sent to change to spa).

**Comment by grgur** [comment]
It's a really hot pool. Some people like geyser hot

Temperatures are random. I could set up a new function for random water temp i guess

**Comment by grgur** [comment]
fixed
