### ISSUE TITLE
When selecting some devices, controls are momentarily rendered

### ISSUE THREAD

**Issue by ModiteDave** [RoboDomo/robodomo-client#43]
Under "Theater" selecting Apple TV and AVR there is a momentary rendering of some controls.
[flash_controls.mov.zip](https://github.com/RoboDomo/robodomo-client/files/3432583/flash_controls.mov.zip)

**Comment by chrndr** [comment]
I think this is caused, at least in part, by some React hooks being used conditionally here:  https://github.com/RoboDomo/robodomo-client/blob/e5c285636e2e456400d9f9d2558a1d0082819593/src/Tablet/Theater/TheaterTab.js#L22-L46
eslint gives warnings on this file:
>`36:15  warning  React Hook "useDenon" may be executed more than once. Possibly because it is called in a loop. React Hooks must be called in the exact same order in every component render`
`react-hooks/rules-of-hooks`
[...]

https://reactjs.org/docs/hooks-rules.html

**Comment by grgur** [comment]
Fixed in #58
