### ISSUE TITLE
Nest: Using the "Set to..." feature, the UI is not updated.

### ISSUE THREAD

**Issue by ModiteDave** [RoboDomo/robodomo-client#44]
Selecting a "Set to..." does not update the UI for the dial control or the "Time To Target"

The MQTT call is made, but is not reflected.

<img width="1495" alt="Screen Shot 2019-07-25 at 1 09 01 PM" src="https://user-images.githubusercontent.com/32716501/61894119-b50c5300-aedd-11e9-871a-d14067fef16b.png">

<img width="711" alt="Screen Shot 2019-07-25 at 1 10 15 PM" src="https://user-images.githubusercontent.com/32716501/61894123-b76ead00-aedd-11e9-9685-2f4df7642c23.png">

**Comment by grgur** [comment]
Fixed
