### ISSUE TITLE
Cannot read property 'autelis' of null

### ISSUE THREAD

**Issue by popescunsergiu** [RoboDomo/robodomo-client#48]
Env:
- Chrome+Win10
- Galaxy Tab S4

SessionId: 884662518ec454a867f5ff1ca39e80adb59df62c

<img width="926" alt="Screenshot 2019-07-26 at 13 43 13" src="https://user-images.githubusercontent.com/8069082/61946720-f79c6100-afab-11e9-8ab9-f27847352bdc.png">
<img width="557" alt="Screenshot 2019-07-26 at 13 42 52" src="https://user-images.githubusercontent.com/8069082/61946721-f79c6100-afab-11e9-9239-d4bd0e9c54c2.png">

Videos were provided via Slack

**Comment by grgur** [comment]
Fixed
