### ISSUE TITLE
State is not correctly persistent for initial app values

### ISSUE THREAD

**Issue by popescunsergiu** [RoboDomo/robodomo-client#49]
Env: all

*Steps to reproduce:*
1. Go to SmartThings (Ceiling Fan Light must be on by default - initial value)
2. Don't change anything
3. Go to Dashboard

*Actual:*
Ceiling Fan Light is Off

*Expected:*
App Initial values shall be consistent across the app

![Screenshot 2019-07-26 at 15 54 12](https://user-images.githubusercontent.com/8069082/61952904-bc0a9280-afbd-11e9-98c3-c0d6c5ff0ee3.png)
![Screenshot 2019-07-26 at 15 54 04](https://user-images.githubusercontent.com/8069082/61952905-bc0a9280-afbd-11e9-8393-7be481557786.png)

**Comment by grgur** [comment]
@popescunsergiu mind checking if this is still the case? Might have been fixed in #59
