### ISSUE TITLE
Autelis Button state does not change correctly

### ISSUE THREAD

**Issue by popescunsergiu** [RoboDomo/robodomo-client#50]
Env: All
SessionId: 25ccc67bc701e19e7e15477ee83d5a46c5f54d00

*Steps to reproduce:*
1 - Go to Autelis page
2. Change Solar to On

*Actual:*
Button shall get enabled

*Expected:*
Button gets stuck in an intermediate state

![Screenshot 2019-07-26 at 16 08 10](https://user-images.githubusercontent.com/8069082/61953731-d80f3380-afbf-11e9-8360-800fc9c9ffa2.png)

A video can be found here: https://automate.browserstack.com/builds/ebf9f4b47206a0890476497f5a1fcdace0625bf2/sessions/660b1bf3c85388762e12d3813c4ea7aa9a5e6733

**Comment by grgur** [comment]
Fixed in #45
