### ISSUE TITLE
Sometimes the app fails to load. The dark grey background is displayed with no content

### ISSUE THREAD

**Issue by popescunsergiu** [RoboDomo/robodomo-client#52]
Env: all
build: latest master

A video can be found at this location: https://automate.browserstack.com/builds/ebf9f4b47206a0890476497f5a1fcdace0625bf2/sessions/0a2c88c4719c2d51f0e4388a59aa5b029024f433#automate_button

**Comment by grgur** [comment]
can no longer replicate. Let's reopen if the issue resurfaces
