### ISSUE TITLE
App state is not consistent

### ISSUE THREAD

**Issue by popescunsergiu** [RoboDomo/robodomo-client#57]
Env: All
Version: Latest

*Steps to reproduce:*
1. Go to http://localhost:3000/smartthings/all
2. Change `Kitchen Light` state and / or dimm value
3. Go to http://localhost:3000/smartthings/kitchen
4. Check `Kitchen Light` state and dimm value

*Expected:*
Shall be the same
*Actual:*
Are different

NOTE: It happens for `Office Light` and `Bathroom Light` also
Found with `RoboDomo MQTT SmartThings page` tests set

![Screenshot 2019-08-01 at 12 14 34](https://user-images.githubusercontent.com/8069082/62281388-5e12fa80-b456-11e9-8fb6-75e2b149174b.png)
![Screenshot 2019-08-01 at 12 14 30](https://user-images.githubusercontent.com/8069082/62281391-5e12fa80-b456-11e9-8597-eb1efec7ea3d.png)

**Comment by grgur** [comment]
fixed in #59
