### ISSUE TITLE
Smartthings UI broken on iPad

### ISSUE THREAD

**Issue by popescunsergiu** [RoboDomo/robodomo-client#64]
Env: iPad Pro 12.9 2018
app: latest

![Screenshot 2019-08-05 at 10 54 51](https://user-images.githubusercontent.com/8069082/62448141-c96b0e00-b76f-11e9-8e8f-a8bfc3132635.png)

https://automate.browserstack.com/builds/32e0580c54cfcbac309693aed2448edfbcb50b34/sessions/d480d22301afe384599c9503f2800768ecd9a49a

**Comment by grgur** [comment]
Looks a lot better now. There are issues with color combos, tho and I'd say it's a global issue, not something related to ST only

**Comment by grgur** [comment]
Replaced this issue with #83
