### ISSUE TITLE
Theater tab - Incorrect behaviour of Activities settings

### ISSUE THREAD

**Issue by popescunsergiu** [RoboDomo/robodomo-client#69]
Env: all
build: latest

*Steps to reproduce:*
1. Go to Theater tab
2. Click on Activities radios

*Actual result:*
Allpe TV and All Off cannot be selected

![bug_01](https://user-images.githubusercontent.com/8069082/62535244-90a46500-b853-11e9-9fea-ea7a758fa0bf.gif)

**Comment by grgur** [comment]
@TulvanAndrei is working on removing the unused sections

**Comment by TulvanAndrei** [comment]
Fixed with #95 .
