### ISSUE TITLE
Pool pump control is tri-state radio buttons

### ISSUE THREAD

**Issue by mschwartz** [RoboDomo/robodomo-client#74]
![image](https://user-images.githubusercontent.com/329637/62545863-574e0400-b817-11e9-838c-3e5299d5e606.png)

The pool pump is either on or off.  If it is on, it is either running (the filter) the pool or spa.

So the control should be something like radio buttons.  One state is off.  One state is pool.  One state is spa.

Technically speaking, there's a valve the switches the water flow from pool to spa when spa is on.

**Comment by grgur** [comment]
each of these toggles changes multiple states. I intentionally mocked two independent pumps, one for each.

**Comment by mschwartz** [comment]
There is only ONE pump.

There's a valve that opens to pump from / to the spa, or when closed pump from the pool

Solar is separate.  That is a heater that can be on or off.  When on, the water is pumped to the roof and heated by the sun, then returned to the pool or spa, depending on if the other valve is open/closed.

**Comment by mschwartz** [comment]
For clarity...

![image](https://user-images.githubusercontent.com/329637/62564624-01d71e80-b83a-11e9-8206-3523c1477436.png)

**Comment by grgur** [comment]
I understand your concern. I believe you're speaking about your local setup? The demo application uses a setup where SPA (whirlpool) and Pool use different pump streams 😄
