### ISSUE TITLE
iOS design tweaks

### ISSUE THREAD

**Issue by grgur** [RoboDomo/robodomo-client#83]
There are a number of styling issues in iOS, mostly related to color contrast. 

#### Steps to replicate in Chrome:
1. Open developer tools
2. Turn on the device toolbar (blue icon)
![image](https://user-images.githubusercontent.com/733074/62620940-dd06a800-b91a-11e9-91d0-6440dac8d6d5.png)

3. Select iPad in the dropdown
![image](https://user-images.githubusercontent.com/733074/62621006-08899280-b91b-11e9-9862-b151823d182e.png)

4. Reload the app

#### Screenshots
Toggle and slider thumbs
![image](https://user-images.githubusercontent.com/733074/62621073-4e465b00-b91b-11e9-99d1-d41d33e4f6c2.png)

Lines under volume icons, low contrast in headings
![image](https://user-images.githubusercontent.com/733074/62621151-7e8df980-b91b-11e9-9b34-46820395edc9.png)

![image](https://user-images.githubusercontent.com/733074/62621213-a67d5d00-b91b-11e9-8d69-bc57435cc412.png)

Poor separation of the number field and an unnecessary line
![image](https://user-images.githubusercontent.com/733074/62621284-cad93980-b91b-11e9-9bfd-55f0f52022f9.png)

Line not needed under the heading
![image](https://user-images.githubusercontent.com/733074/62621356-f2300680-b91b-11e9-91f5-924d4722075a.png)

**Comment by TulvanAndrei** [comment]
@grgur The issues explained here were fixed after this commit "Layout improvements for smaller screens (#78 )".

**Comment by TulvanAndrei** [comment]
Closing issue, this was fixed in this PR #86
